language: java
jdk:
  - oraclejdk8
after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
  - bash <(curl -s https://codecov.io/bash)
  
env:
  global:
    - CODECOV_TOKEN=df8c95c1-96ba-41ff-aa20-03cc97711400